### ISSUE TITLE
Change picture and name

### ISSUE THREAD

**Issue by madjin** [webaverse/ethereum-bot#24]
New profile pic (more on the drive):

- https://webaverse.com/img/bot.gif
- https://cdn.discordapp.com/attachments/684167488963215364/878749659584151602/01.png

New name:

- OMI-bot
  - Maybe ok?
- Exobot
  - OG homage!
  - Inverse of 0x

**Comment by avaer** [comment]
> https://webaverse.com/img/bot.gif
is 404 for me

**Comment by madjin** [comment]
> > https://webaverse.com/img/bot.gif
> > is 404 for me

works for me

**Comment by vyrnix9582046173** [comment]
>  jin: i think exobot is a good name for it..
> x0, like 0x, like ethereum
>  it has a little compartment too

> metavly: That's a cool branding for it. 
> I think because the bot has "Playing webaverse.com" on it, we can afford to be creative with the name/profile pic branding since people will know it is powered by Webaverse.
  
![image](https://user-images.githubusercontent.com/29695350/130675922-e21b4f6b-c3b6-4409-839a-66b7d2441e97.png)

**Comment by avaer** [comment]
Exobot and this pic both sound good. 0x/Exo is a cool coincidence.

**Comment by vyrnix9582046173** [comment]
Added because I happened to be in the settings for the bot. Another improvement that should be done is adding the presence "Playing webaverse.com" so that it is associated with Webaverse. See #34
